FROM sinapsis-nvidia:base
# install essential packages
RUN apt-get update && apt-get install -y ffmpeg python3.10-dev

COPY . /app/
WORKDIR /app

RUN uv sync --frozen  --all-extras --all-packages
RUN uv build --all-packages

# install the generated wheels for this app
RUN uv pip install /app/dist/sinapsis_*none-any.whl
