agent:
  name: my_test_agent
templates:
- template_name: InputTemplate
  class_name: InputTemplate
  attributes: {}

- template_name: fetch_california_housingWrapper
  class_name: fetch_california_housingWrapper
  template_input: InputTemplate
  attributes:
    split_dataset: true
    fetch_california_housing:
      data_home: null
      download_if_missing: true
      return_X_y: false
      as_frame: true

- template_name: XGBRegressorWrapper
  class_name: XGBRegressorWrapper
  template_input: fetch_california_housingWrapper
  attributes:
    generic_field_key: fetch_california_housingWrapper
    model_save_path: "artifacts/xgb_regressor.model"
    xgbregressor_init:
      n_estimators: 100
      max_depth: 5
      learning_rate: 0.1
      objective: 'reg:squarederror'
      booster: 'gbtree'
      tree_method: 'auto'
      n_jobs: -1
      random_state: 42
