agent:
  name: sklearn_tree_models_agent
  description: agent to train a DecisionTreeClassifier using the load_wine dataset

templates:
- template_name: InputTemplate
  class_name: InputTemplate
  attributes: {}

- template_name: load_wineWrapper
  class_name: load_wineWrapper
  template_input: InputTemplate
  attributes:
    split_dataset: true
    train_size: 0.8
    load_wine:
      return_X_y: false
      as_frame: true

- template_name: DecisionTreeClassifierWrapper
  class_name: DecisionTreeClassifierWrapper
  template_input: load_wineWrapper
  attributes:
    generic_field_key: load_wineWrapper
    model_save_path: "artifacts/decision_tree.joblib"
    decisiontreeclassifier_init:
      criterion: 'gini'
      splitter: 'best'
      max_depth: 5
      min_samples_split: 2
      min_samples_leaf: 1
      min_weight_fraction_leaf: 0.0
      max_features: null
      random_state: 42
      max_leaf_nodes: null
      min_impurity_decrease: 0.0
      class_weight: null
      ccp_alpha: 0.0
