agent:
  name: sklearn_manifold_agent
  description: agent to train a TSNE from sklearn using the load_digits dataset

templates:
- template_name: InputTemplate
  class_name: InputTemplate
  attributes: {}

- template_name: load_digitsWrapper
  class_name: load_digitsWrapper
  template_input: InputTemplate
  attributes:
    split_dataset: true
    train_size: 0.8
    load_digits:
      n_class: 10
      return_X_y: false
      as_frame: true

- template_name: TSNEWrapper
  class_name: TSNEWrapper
  template_input: load_digitsWrapper
  attributes:
    generic_field_key: load_digitsWrapper
    tsne_init:
      n_components: 2
      perplexity: 30.0
      early_exaggeration: 12.0
      learning_rate: 200.0
      n_iter: 1000
      n_iter_without_progress: 300
      min_grad_norm: 0.0000001
      metric: 'euclidean'
      init: 'random'
      random_state: 42
      method: 'barnes_hut'
      angle: 0.5
      n_jobs: null
