agent:
  name: sklearn_neighbors_models_agent

templates:
- template_name: InputTemplate
  class_name: InputTemplate
  attributes: {}
- template_name: load_iris
  class_name: load_irisWrapper
  template_input: InputTemplate
  attributes:
    split_dataset: false
    load_iris:
      return_X_y: false
      as_frame: true
- template_name: SKLearnInference
  class_name: SKLearnInference
  template_input: load_iris
  attributes:
    model_path: 'artifacts/knn_classifier.joblib'
    generic_field_key: 'load_iris'
