agent:
  name: sklearn_neighbors_models_agent

templates:
- template_name: InputTemplate
  class_name: InputTemplate
  attributes: {}
- template_name: load_iris
  class_name: load_irisWrapper
  template_input: InputTemplate
  attributes:
    split_dataset: false
    load_iris:
      return_X_y: false
      as_frame: true
- template_name: TabularDatasetSplitter
  class_name: TabularDatasetSplitter
  template_input: load_iris
  attributes:
    train_size: 0.8
    generic_data_extract_key: load_iris
    generic_data_feature_key: "sepal length (cm)"
- template_name: Manifold
  class_name: IsomapWrapper
  template_input: TabularDatasetSplitter
  attributes:
    generic_field_key: TabularDatasetSplitter
    isomap_init:
      n_neighbors: 10
      n_components: 2