agent:
  name: sklearn_neighbors_models_agent

templates:
- template_name: InputTemplate
  class_name: InputTemplate
  attributes: {}
- template_name: fetch_california_housingWrapper
  class_name: fetch_california_housingWrapper
  template_input: InputTemplate
  attributes:
    split_dataset: false
    fetch_california_housing:
      data_home: null
      download_if_missing: true
      return_X_y: false
      as_frame: true
- template_name: XGBoostInference
  class_name: XGBoostInference
  template_input: fetch_california_housingWrapper
  attributes:
    model_path: 'artifacts/xgb_regressor.model'
    generic_field_key: 'fetch_california_housingWrapper'
